import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React from "react"
import { NextUIProviders, Navbar } from "./_components"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const RootLayout = ({
    children,
}: {
  children: React.ReactNode
}) => (
    <html lang="en">
        <body className={inter.className}>
            <NextUIProviders> 
                <Navbar />
                {children}
            </NextUIProviders>
        </body>
    </html>
)
export default RootLayout
